
apiVersion: apps/v1
kind: Deployment
metadata:
  name: role
spec:
  replicas: 1
  selector:
    matchLabels:
      app: role
  template:
    metadata:
      labels:
        app: role
    spec:
      containers:
        - image: mmassolit/playback
          name: role
          ports:
            - containerPort: 8081
              name: role
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://127.0.0.1:5432/role_service"
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USERNAME
              value: "video_sharing_test"